/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.viewobjects.Error;
import io.swagger.model.viewobjects.Leave;
import io.swagger.model.viewobjects.Leaves;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-04-23T14:46:36.951Z[GMT]")
@Validated
public interface LeavesApi {

    @Operation(summary = "Approve a leave", description = "", security = {
        @SecurityRequirement(name = "basicAuth")    }, tags={ "leaves" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Approval response", content = @Content(schema = @Schema(implementation = Boolean.class))),
        
        @ApiResponse(responseCode = "401", description = "Authentication information is missing or invalid"),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/leaves/{leaveId}/approve",
        produces = { "text/plain", "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Boolean> approveLeaves(@Parameter(in = ParameterIn.PATH, description = "The id of the leave to retrieve", required=true, schema=@Schema()) @PathVariable("leaveId") String leaveId);


    @Operation(summary = "List all leaves", description = "", security = {
        @SecurityRequirement(name = "basicAuth")    }, tags={ "leaves" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "A paged array of leaves", content = @Content(schema = @Schema(implementation = Leaves.class))),
        
        @ApiResponse(responseCode = "401", description = "Authentication information is missing or invalid"),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/leaves",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Leaves> listLeaves(@Parameter(in = ParameterIn.QUERY, description = "status of the leave REQUESTED,APPROVED,DENIED" ,schema=@Schema(allowableValues={ "REQUESTED", "APPROVED", "DENIED" }
)) @Valid @RequestParam(value = "status", required = false) String status, @Parameter(in = ParameterIn.QUERY, description = "if true returns leaves of reportees by name for approval" ,schema=@Schema()) @Valid @RequestParam(value = "reportee", required = false) String reportee, @Parameter(in = ParameterIn.QUERY, description = "How many items to return at one time (max 100)" ,schema=@Schema()) @Valid @RequestParam(value = "limit", required = false) Integer limit, @Parameter(in = ParameterIn.QUERY, description = "What is the current pagination page" ,schema=@Schema()) @Valid @RequestParam(value = "page", required = false) Integer page);


    @Operation(summary = "Request a leave", description = "", security = {
        @SecurityRequirement(name = "basicAuth")    }, tags={ "leaves" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Null response"),
        
        @ApiResponse(responseCode = "401", description = "Authentication information is missing or invalid"),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/leaves",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> requestLeave(@Parameter(in = ParameterIn.DEFAULT, description = "Send the Leave Object", required=true, schema=@Schema()) @Valid @RequestBody Leave body);


    @Operation(summary = "Info for a specific leave", description = "", security = {
        @SecurityRequirement(name = "basicAuth")    }, tags={ "leaves" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = @Content(schema = @Schema(implementation = Leave.class))),
        
        @ApiResponse(responseCode = "401", description = "Authentication information is missing or invalid"),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/leaves/{leaveId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Leave> showLeaveById(@Parameter(in = ParameterIn.PATH, description = "The id of the leave to retrieve", required=true, schema=@Schema()) @PathVariable("leaveId") String leaveId);

}

